#!/bin/bash


required_packages=(
  "@nuxt/utils-edge"
  "consola"
  "extract-css-chunks-webpack-plugin"
  "friendly-errors-webpack-plugin"
  "glob"
  "hash-sum"
  "hard-source-webpack-plugin"
  "html-webpack-plugin"
  "memory-fs"
  "optimize-css-assets-webpack-plugin"
  "pify"
  "pnp-webpack-plugin"
  "querystring"
  "semver"
  "terser-webpack-plugin"
  "thread-loader"
  "time-fix-plugin"
  "ufo"
  "upath"
  "vue-loader"
  "watchpack"
  "webpack"
  "webpack-bundle-analyzer"
  "webpack-dev-middleware"
  "webpack-hot-middleware"
  "webpackbar"
)


for package in "${required_packages[@]}"; do
  npm install "$package"
done